---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: credentialsrequest-pruner
  namespace: openshift-sre-pruning
spec:
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Replace
  schedule: "0 */1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: sre-pruner-sa
          restartPolicy: Never
          containers:
          - name: credentialsrequest-pruner
            image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
            imagePullPolicy: Always
            args:
            - /bin/bash
            - -c
            - >-
              oc delete
              credentialsrequest/cloud-ingress-operator-credentials
              secret/cloud-ingress-operator-credentials
              --namespace=openshift-cloud-ingress-operator
              --ignore-not-found
